- kind: Secret
  apiVersion: v1
  metadata:
    name: ${NAME}
    annotations:
      template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
  stringData:
    database-admin-password: ${MONGODB_ADMIN_PASSWORD}
    database-password: ${MONGODB_PASSWORD}
    database-user: ${MONGODB_USER}
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: autosuggest-app-deployment
  labels:
    app: autosuggest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autosuggest-app
  template:
    metadata:
      labels:
        app: autosuggest-app
        tier: frontend
    spec:
      containers:
      - name: autosuggest-app
        image: "eu.gcr.io/autosuggest-194816/autosuggest-app:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: autosuggest-app-service
spec:
  selector:
    app: autosuggest-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30061
  type: LoadBalancer